name: KillCommand
version: '1.0'
main: f3f5.killcommand.KillCommand
commands:
  kill:
    description: It kills the player passed and if none, kills the command sender.
    usage: <command>
  suicide:
    description: It kills the player passed and if none, kills the command sender.
    usage: <command>